# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d665cfe49ecd212dc21be7264601e22055dcb309c4c66a2735eb6acabf9e1a56db62c237f2daf9b5cf484d16a66fcbb9fbdbebaaa053ac8f06db9a611352c03

test:
  secret_key_base: 1a02d77c8961cb26d5e7fb9dca29ce7916c6899dce5b485d82f0ce5b78e3ad7d2310ca4d52b734ed37dcfcd4d8a3aa906722870a6d2941244a94fd956c5e66c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
